#ifndef __PHP_MUPARSER_H__
#define __PHP_MUPARSER_H__

MUPARSER_STARTUP_FUNCTION(parser);
MUPARSER_SHUTDOWN_FUNCTION(parser);

MUPARSER_ACTIVATE_FUNCTION(parser);
MUPARSER_DEACTIVATE_FUNCTION(parser);

#endif
